name: Linter & Tests

on: [push]

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v1
        with:
          go-version: '1.15.x'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
      - name: Install golint
        run: go get -v golang.org/x/lint/golint
      - name: Run golint
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          golint ./...

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v1
        with:
          go-version: '1.15.x'
      - name: Run tests
        run: go test -v ./...
