name: Linter & Tests

on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v1
        with:
          go-version: '1.15.x'
      - name: Run tests
        run: go test -v ./...
